const state={recipes:[],selected:null};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!response.ok){let message=await response.text();try{message=JSON.parse(message).error||message}catch{}throw new Error(message)}return response.json()}
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("show"),2600)}
function lines(values=[]){return values.join("\n")}
function ingredientsText(values=[]){return values.map(item=>`${item.name} | ${item.quantity} | ${item.unit}`).join("\n")}
function parseIngredients(text){return text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const parts=line.split("|").map(value=>value.trim());const quantity=Number(parts[1]);if(parts.length<3||!parts[0]||!Number.isFinite(quantity)||quantity<=0||!parts[2])throw new Error(`Ingredient line ${index+1} must be: name | quantity | unit`);return{name:parts[0],quantity,unit:parts[2]}})}
function parseLines(text){return text.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)}
function readForm(){const form=$("#recipe-form"),data=new FormData(form);return{id:Number(data.get("id")||0),name:String(data.get("name")||"").trim(),category:String(data.get("category")||"").trim(),servings:Number(data.get("servings")||2),minutes:Number(data.get("minutes")||30),ingredients:parseIngredients(String(data.get("ingredients")||"")),steps:parseLines(String(data.get("steps")||"")),equipment:parseLines(String(data.get("equipment")||"")),sourcePath:String(data.get("sourcePath")||"").trim(),extractionNotes:String(data.get("extractionNotes")||"").trim(),verified:data.get("verified")==="on"}}
function fill(recipe){state.selected=recipe;const form=$("#recipe-form");for(const key of["id","name","category","servings","minutes","sourcePath","extractionNotes"])form.elements[key].value=recipe[key]??"";form.elements.ingredients.value=ingredientsText(recipe.ingredients);form.elements.steps.value=lines(recipe.steps);form.elements.equipment.value=lines(recipe.equipment);form.elements.verified.checked=!!recipe.verified;$("#editor-title").textContent=recipe.name||"New recipe draft";renderList()}
function emptyRecipe(){return{id:0,name:"",category:"",servings:2,minutes:30,ingredients:[],steps:[],equipment:[],sourcePath:"",extractionNotes:"",verified:false}}
function renderList(){const filter=$("#recipe-filter").value;const recipes=state.recipes.filter(recipe=>filter==="all"||(filter==="verified")===recipe.verified);$("#recipe-list").innerHTML=recipes.map(recipe=>`<button class="recipe-button ${state.selected?.name===recipe.name?"active":""}" data-name="${esc(recipe.name)}"><strong>${esc(recipe.name)}</strong><small>${recipe.verified?"Verified":"Draft"} · ${recipe.minutes} minutes</small></button>`).join("")||"<p>No recipes match this filter.</p>";document.querySelectorAll(".recipe-button").forEach(button=>button.onclick=()=>fill(state.recipes.find(recipe=>recipe.name===button.dataset.name)))}
async function load(){state.recipes=await api("/api/admin/recipes");renderList();if(!state.selected&&state.recipes.length)fill(state.recipes[0])}
async function loadUnitRules(){const result=await api("/api/units");$("#unit-rules").innerHTML=`<p><strong>Selectable units:</strong> ${result.units.map(esc).join(", ")}</p>`+result.rules.map(rule=>`<div class="rule-row"><strong>${esc(rule.family)}: ${esc(rule.fromUnit)} → ${esc(rule.toUnit)}</strong><span>× ${rule.multiplier}${rule.approximate?" · APPROXIMATE":""}</span><small>${esc(rule.notes)}</small></div>`).join("")}
$("#new-recipe").onclick=()=>fill(emptyRecipe());
$("#recipe-filter").onchange=renderList;
$("#recipe-form").onsubmit=async event=>{event.preventDefault();try{const saved=await api("/api/admin/recipes",{method:"PUT",body:JSON.stringify(readForm())});state.selected=saved;await load();fill(state.recipes.find(recipe=>recipe.name===saved.name));toast(saved.verified?"Verified recipe saved.":"Recipe draft saved.")}catch(error){toast(error.message)}};
$("#ai-draft").onclick=async()=>{const instructions=$("#ai-instructions").value.trim();if(!instructions){toast("Describe what the AI should add or correct.");return}$("#ai-status").textContent="Generating a local editable draft...";try{let recipe;try{recipe=readForm()}catch{recipe=state.selected||emptyRecipe()}const draft=await api("/api/admin/recipes/ai-draft",{method:"POST",body:JSON.stringify({recipe,instructions})});fill({...draft,verified:false});$("#ai-status").textContent="Draft generated. Review every field, then save or verify it manually."}catch(error){$("#ai-status").textContent=`AI draft failed: ${error.message}`}};
Promise.all([load(),loadUnitRules()]).catch(error=>toast(error.message));
