const state={items:[],meals:[],shopping:[],photoData:null,stream:null,weekStart:mondayOf(new Date()),conversationId:localStorage.getItem("hearthConversationId")||"web-home",autoSkills:localStorage.getItem("hearthAutoSkills")!=="false",selectedSkillIds:JSON.parse(localStorage.getItem("hearthSelectedSkills")||"[]")};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function iso(d){return d.toISOString().slice(0,10)} function mondayOf(v){const d=new Date(v);d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d} function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x} function weekEnd(){return addDays(state.weekStart,6)}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});if(!r.ok)throw new Error(await r.text()||`Request failed: ${r.status}`);return r.status===204?null:r.json()}
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),2300)}
function showView(id){$$(".view").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav-button").forEach(x=>x.classList.toggle("active",x.dataset.view===id));if(id==="shopping")loadShopping()}
function renderAssistantMessage(role,content,extra=""){const empty=$(".assistant-empty");if(empty)empty.remove();const bubble=document.createElement("div");bubble.className=`chat-bubble ${role} ${extra}`;bubble.textContent=content;$("#assistant-messages").appendChild(bubble);$("#assistant-messages").scrollTop=$("#assistant-messages").scrollHeight;return bubble}
async function loadConversations(){const conversations=await api("/api/assistant/conversations");const known=conversations.some(c=>c.id===state.conversationId);$("#conversation-picker").innerHTML=`<option value="${esc(state.conversationId)}">${known?"Current chat":"New chat"}</option>`+conversations.filter(c=>c.id!==state.conversationId).map(c=>`<option value="${esc(c.id)}">${esc(c.title||"New chat")}</option>`).join("")}
async function loadAssistant(){const[status,messages]=await Promise.all([api("/api/assistant/status"),api(`/api/assistant/messages?conversationId=${encodeURIComponent(state.conversationId)}`),loadConversations()]);$("#assistant-provider").textContent=status.available?status.provider:"Local reasoning model is not installed";$("#reasoning-model").innerHTML=status.models.map(m=>`<option ${m===status.selectedModel?"selected":""}>${esc(m)}</option>`).join("");$("#vision-model").innerHTML=status.visionModels.length?status.visionModels.map(m=>`<option ${m===status.selectedVisionModel?"selected":""}>${esc(m)}</option>`).join(""):'<option>No vision model installed</option>';$("#vision-model").disabled=!status.visionModels.length;$("#auto-skills").checked=state.autoSkills;$("#skill-picker").innerHTML=status.skills.length?status.skills.map(s=>`<option value="${esc(s.id)}" ${state.selectedSkillIds.includes(s.id)?"selected":""} title="${esc(s.description)}">${esc(s.name)}</option>`).join(""):'<option disabled>No additional skills installed</option>';$("#skill-picker").disabled=state.autoSkills||!status.skills.length;$("#assistant-messages").innerHTML="";if(messages.length)messages.forEach(m=>renderAssistantMessage(m.role,m.content));else $("#assistant-messages").innerHTML='<div class="assistant-empty"><h3>Your home, in context.</h3><p>Ask what you can cook, what is running low, what expires soon, or how to plan the week.</p></div>';$("#assistant-send").disabled=!status.available}
async function streamAssistant(message,bubble){const response=await fetch("/api/assistant/chat-stream",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,conversationId:state.conversationId,selectedSkillIds:state.selectedSkillIds,autoSkills:state.autoSkills})});if(!response.ok)throw new Error((await response.text())||"Generation failed");bubble.textContent="";bubble.classList.remove("pending");window.beginStreamingSpeech?.();const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const{value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done}).replace(/\r/g,"");let boundary;while((boundary=buffer.indexOf("\n\n"))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);let event="message",data="";for(const line of block.split("\n")){if(line.startsWith("event:"))event=line.slice(6).trim();if(line.startsWith("data:"))data+=line.slice(5).trim()}if(!data)continue;const payload=JSON.parse(data);if(event==="token"){bubble.textContent+=payload.text;window.pushStreamingSpeech?.(payload.text);$("#assistant-messages").scrollTop=$("#assistant-messages").scrollHeight}else if(event==="error")throw new Error(payload.message);else if(event==="done"){window.finishStreamingSpeech?.()}}if(done)break}loadConversations()}
async function refresh(){const from=iso(state.weekStart),to=iso(weekEnd());[state.items,state.meals,state.shopping]=await Promise.all([api("/api/items"),api(`/api/meals?from=${from}&to=${to}`),api(`/api/shopping?from=${from}&to=${to}`)]);renderAll()}
function renderAll(){renderInventory();renderMeals();renderShopping();renderDashboard();$("#week-label").textContent=`${state.weekStart.toLocaleDateString(undefined,{month:"short",day:"numeric"})} – ${weekEnd().toLocaleDateString(undefined,{month:"short",day:"numeric"})}`;$("#shopping-week").textContent=$("#week-label").textContent}
function renderDashboard(){const low=state.items.filter(i=>+i.quantity<=+i.minQuantity);$("#stat-items").textContent=state.items.length;$("#stat-low").textContent=low.length;$("#stat-meals").textContent=state.meals.length;$("#stat-shopping").textContent=state.shopping.length;$("#low-preview").innerHTML=low.length?low.slice(0,4).map(i=>`<div class="preview-row"><strong>${esc(i.name)}</strong><span class="badge">${i.quantity} ${esc(i.unit||"")} left</span></div>`).join(""):"Nothing is running low.";$("#meal-preview").innerHTML=state.meals.length?state.meals.slice(0,4).map(m=>`<div class="preview-row"><div><strong>${esc(m.recipeName)}</strong><div class="item-meta">${esc(m.mealType)} · ${m.mealDate}</div></div><span>${m.servings} servings</span></div>`).join(""):"No meals planned yet."}
function renderInventory(){const search=$("#inventory-search").value.toLowerCase(),category=$("#inventory-category").value,categories=[...new Set(state.items.map(i=>i.category).filter(Boolean))].sort(),current=$("#inventory-category").value;$("#inventory-category").innerHTML=`<option value="">All categories</option>${categories.map(c=>`<option ${c===current?"selected":""}>${esc(c)}</option>`).join("")}`;const filtered=state.items.filter(i=>(!category||i.category===category)&&[i.name,i.category,i.location].join(" ").toLowerCase().includes(search));$("#inventory-grid").innerHTML=filtered.length?filtered.map(i=>`<article class="item-card">${i.imageFilename?`<img class="item-photo" src="/photos/${encodeURIComponent(i.imageFilename)}" alt="${esc(i.name)}">`:`<div class="item-photo placeholder">${esc(i.name.slice(0,1).toUpperCase())}</div>`}<div class="item-body"><div class="item-meta">${esc(i.category||"Uncategorized")} · ${esc(i.location||"No location")}</div><h3>${esc(i.name)}</h3><div class="quantity"><strong>${i.quantity}</strong> ${esc(i.unit||"")}</div>${+i.quantity<=+i.minQuantity?'<span class="badge">Running low</span>':""}</div><div class="card-actions"><button data-edit="${i.id}">Edit</button><button data-delete="${i.id}">Delete</button></div></article>`).join(""):'<div class="empty">No matching items. Add your first household item.</div>'}
function renderMeals(){const by=state.meals.reduce((a,m)=>((a[m.mealDate]??=[]).push(m),a),{});$("#meal-days").innerHTML=Array.from({length:7},(_,n)=>{const date=addDays(state.weekStart,n),key=iso(date),meals=by[key]||[];return `<article class="day-card"><div class="day-head">${date.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</div>${meals.length?meals.map(m=>`<div class="meal-row"><div><span>${esc(m.mealType)}</span><strong>${esc(m.recipeName)}</strong><span>${m.servings} servings · ${m.ingredients.length} ingredients</span></div><button class="delete-meal" data-delete-meal="${m.id}">Remove</button></div>`).join(""):'<div class="empty" style="padding:15px">Open — add a meal</div>'}</article>`}).join("");const d=$('[name="mealDate"]',$("#meal-form"));if(!d.value||d.value<iso(state.weekStart)||d.value>iso(weekEnd()))d.value=iso(state.weekStart)}
function renderShopping(){$("#shopping-list").innerHTML=state.shopping.length?state.shopping.map(x=>`<label class="shopping-row"><input type="checkbox"><div class="shop-name"><strong>${esc(x.name)}</strong><span>Need ${x.needed}; have ${x.available}</span></div><div class="shop-qty">${+x.toBuy.toFixed(2)} ${esc(x.unit)}</div></label>`).join(""):'<div class="empty" style="padding:28px">You have everything required for this week’s planned meals.</div>'}
async function loadShopping(){state.shopping=await api(`/api/shopping?from=${iso(state.weekStart)}&to=${iso(weekEnd())}`);renderShopping();renderDashboard()}
function stopCamera(){if(state.stream)state.stream.getTracks().forEach(t=>t.stop());state.stream=null;$("#camera-video").hidden=true;$("#capture-photo").hidden=true;$("#start-camera").textContent="Start camera"}
function openItem(item=null){stopCamera();const f=$("#item-form");f.reset();state.photoData=null;$("#photo-preview").hidden=true;$("#camera-placeholder").hidden=false;$("#item-dialog-title").textContent=item?"Edit item":"Add an item";if(item)Object.entries(item).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??""});if(item?.imageFilename){$("#photo-preview").src=`/photos/${encodeURIComponent(item.imageFilename)}`;$("#photo-preview").hidden=false;$("#camera-placeholder").hidden=true}$("#item-dialog").showModal()}
async function startCamera(){try{stopCamera();state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});$("#camera-video").srcObject=state.stream;$("#camera-video").hidden=false;$("#photo-preview").hidden=true;$("#camera-placeholder").hidden=true;$("#capture-photo").hidden=false;$("#start-camera").textContent="Restart camera"}catch(e){toast(`Camera unavailable: ${e.message}`)}}
function capturePhoto(){const v=$("#camera-video"),c=$("#camera-canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);state.photoData=c.toDataURL("image/jpeg",.82);$("#photo-preview").src=state.photoData;$("#photo-preview").hidden=false;stopCamera();$("#camera-placeholder").hidden=true}
document.addEventListener("click",async e=>{const nav=e.target.closest("[data-view]");if(nav)showView(nav.dataset.view);const go=e.target.closest("[data-go]");if(go)showView(go.dataset.go);if(e.target.closest("[data-open-item]"))openItem();if(e.target.closest("[data-close]")){stopCamera();$("#item-dialog").close()}const edit=e.target.closest("[data-edit]");if(edit)openItem(state.items.find(i=>i.id===+edit.dataset.edit));const rem=e.target.closest("[data-delete]");if(rem&&confirm("Delete this inventory item?")){await api(`/api/items?id=${rem.dataset.delete}`,{method:"DELETE"});await refresh();toast("Item deleted")}const rm=e.target.closest("[data-delete-meal]");if(rm){await api(`/api/meals?id=${rm.dataset.deleteMeal}`,{method:"DELETE"});await refresh();toast("Meal removed")}});
$("#inventory-search").addEventListener("input",renderInventory);$("#inventory-category").addEventListener("change",renderInventory);$("#start-camera").addEventListener("click",startCamera);$("#capture-photo").addEventListener("click",capturePhoto);$("#item-dialog").addEventListener("close",stopCamera);$("#week-prev").addEventListener("click",async()=>{state.weekStart=addDays(state.weekStart,-7);await refresh()});$("#week-next").addEventListener("click",async()=>{state.weekStart=addDays(state.weekStart,7);await refresh()});
$("#copy-shopping").addEventListener("click",async()=>{await navigator.clipboard.writeText(state.shopping.map(x=>`${x.name}: ${+x.toBuy.toFixed(2)} ${x.unit}`).join("\n"));toast("Shopping list copied")});
$("#item-form").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=d.id?+d.id:null;["quantity","minQuantity"].forEach(k=>d[k]=+(d[k]||0));d.photoData=state.photoData;await api("/api/items",{method:d.id?"PUT":"POST",body:JSON.stringify(d)});stopCamera();$("#item-dialog").close();await refresh();toast("Item saved")});
$("#meal-form").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.id=null;d.servings=+(d.servings||1);d.ingredients=d.ingredients.split("\n").filter(Boolean).map(line=>{const[name,quantity="1",unit="count"]=line.split("|").map(x=>x.trim());return{name,quantity:+quantity,unit}});await api("/api/meals",{method:"POST",body:JSON.stringify(d)});e.target.reset();await refresh();toast("Meal added")});
$("#reasoning-model").addEventListener("change",async e=>{const status=await api("/api/assistant/model",{method:"POST",body:JSON.stringify({filename:e.target.value})});$("#assistant-provider").textContent=status.provider;toast("Reasoning model changed. It will load with the next question.")});
$("#vision-model").addEventListener("change",async e=>{await api("/api/assistant/vision-model",{method:"POST",body:JSON.stringify({filename:e.target.value})});toast("Vision model selection saved independently.")});
$("#assistant-form").addEventListener("submit",async e=>{e.preventDefault();const field=e.target.elements.message,text=field.value.trim();if(!text)return;renderAssistantMessage("user",text);field.value="";const pending=renderAssistantMessage("assistant","Loading the selected model and thinking locally…","pending");$("#assistant-send").disabled=true;try{await streamAssistant(text,pending)}catch(error){pending.textContent=`Assistant error: ${error.message}`;window.finishStreamingSpeech?.()}finally{$("#assistant-send").disabled=false;field.focus()}});
$("#new-chat").addEventListener("click",async()=>{const result=await api("/api/assistant/conversations",{method:"POST",body:"{}"});state.conversationId=result.id;localStorage.setItem("hearthConversationId",result.id);await loadAssistant();toast("New chat started")});
$("#clear-chat").addEventListener("click",async()=>{if(!confirm("Clear every message in this chat?"))return;await api(`/api/assistant/conversations/${encodeURIComponent(state.conversationId)}`,{method:"DELETE"});await loadAssistant();toast("Chat cleared")});
$("#conversation-picker").addEventListener("change",async e=>{state.conversationId=e.target.value;localStorage.setItem("hearthConversationId",state.conversationId);await loadAssistant()});
$("#auto-skills").addEventListener("change",e=>{state.autoSkills=e.target.checked;localStorage.setItem("hearthAutoSkills",String(state.autoSkills));$("#skill-picker").disabled=state.autoSkills;toast(state.autoSkills?"Skills will be selected from the question.":"Choose one or more skills manually.")});
$("#skill-picker").addEventListener("change",e=>{state.selectedSkillIds=[...e.target.selectedOptions].map(option=>option.value);localStorage.setItem("hearthSelectedSkills",JSON.stringify(state.selectedSkillIds))});
Promise.all([refresh(),loadAssistant()]).catch(e=>toast(e.message));
