server.address=${PA_SERVER_ADDRESS:127.0.0.1}
server.port=8787
server.ssl.enabled=${PA_HTTPS:false}
server.ssl.key-store=${PA_KEYSTORE:}
server.ssl.key-store-password=${PA_KEYSTORE_PASSWORD:}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=personal-assistant
spring.application.name=personal-assistant
personalassistant.security.pin=${PA_ACCESS_PIN:}
spring.web.resources.static-locations=classpath:/web/
spring.jackson.deserialization.fail-on-unknown-properties=false
server.error.include-message=always
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=16MB
