server.address=127.0.0.1
server.port=8787
spring.application.name=personal-assistant
spring.web.resources.static-locations=classpath:/web/
spring.jackson.deserialization.fail-on-unknown-properties=false
server.error.include-message=always
